theme: jekyll-theme-hacker
title: Credit Converters are proud to present the greatest tragedy in the history of Hackathons: a boring website.
description: On this page, I swore I would indulge you! It's a promise I'll make sure will fall through!
